baseURL = "https://jtattersall.net"
languageCode = "en-gb"
title = "James Tattersall"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    version = "3.0.2"
    contactEmail = "contact@jtattersall.net"